### ISSUE TITLE
Crashes when it can't find the tmp dir.

### ISSUE THREAD

**Issue by choffee** [flathub/com.spotify.Client#48]
The client starts up and shows the main window then crashes with the following error:

boost::filesystem::temp_directory_path: Not a directory: "/tmp/user/1000"

my TMPDIR variable is set to /tmp/user/1000, I assume by something in my setup.

If I run the client with the extra parameter --filesystem=/tmp/user/1000 it works fine.

There is mention on the flatpak site about using a shell script to fix this. Could this maybe be added to the python wrapper?
http://docs.flatpak.org/en/latest/sandbox-permissions.html

> If an application uses $TMPDIR to contain lock files or shared files with other processes, it is recommended to create a wrapper script that sets it to $XDG_CACHE_HOME.

**Comment by TingPing** [comment]
> my TMPVAR variable is set to /tmp/user/1000, I assume buy something in my setup.

Did you mean `TMPDIR`?

**Comment by choffee** [comment]
Yes Sorry. TMPDIR.

**Comment by TingPing** [comment]
I'd say this is mostly a bug of flatpak since it should unset that (https://github.com/flatpak/flatpak/issues/987) but if you confirm `flatpak run --env=TMPDIR= com.spotifiy.Client` works I can add that I suppose.

**Comment by choffee** [comment]
Yes running with the exact command you gave works as well.

It does feel like a flatpak error but sounds like setting TMPDIR to XDG_CACHE_HOME in the startup should fix it.

**Comment by TingPing** [comment]
AFAICT it doesn't store any data meant to be shared, so unsetting the env var is the better solution.

**Comment by kkeijzer** [comment]
I am still having this exact problem with version 1.1.5.153 from Flathub.

```
kevin@vanadium:~$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: 22:36:47.564: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
kevin@vanadium:~$ terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::temp_directory_path: Not a directory: "/tmp/user/1000"
```

I have `libpam-tmpdir` installed, which probably sets the `TMPDIR` to `/tmp/user/1000`. I'd rather not uninstall it, because I prefer `/tmp` to be separated between users.

Changing the `TMPDIR` variable, however, does not help:

```
kevin@vanadium:~$ export TMPDIR=/tmp
kevin@vanadium:~$ echo $TMPDIR
/tmp
kevin@vanadium:~$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: 22:39:40.129: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
kevin@vanadium:~$ terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::temp_directory_path: Not a directory: "/tmp/user/1000"
```
Nor does unsetting it:

```
kevin@vanadium:~$ export TMPDIR=
kevin@vanadium:~$ echo $TMPDIR 

kevin@vanadium:~$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: 22:40:39.462: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
kevin@vanadium:~$ terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::temp_directory_path: Not a directory: "/tmp/user/1000"
```

**Comment by Erick555** [comment]
Try: `flatpak run --env=TEMPDIR= --env=TMP= --env=TMPDIR=  com.spotify.Client
`

**Comment by kkeijzer** [comment]
> Try: `flatpak run --env=TEMPDIR= --env=TMP= --env=TMPDIR= com.spotify.Client `

This does not resolve the problem. The error persists and the client crashes after a few seconds.

**Comment by Erick555** [comment]
Does spotify work if you disable `libpam-tmpdir`?

**Comment by kkeijzer** [comment]
Yes, it works fine if I do so, but I would really rather not remove this security feature.

**Comment by Cherkah** [comment]
same issue as previous.
libpam-tmpdir = installed

after logging, i've to open spotify three times to remain it works. if do not, the app crash!

`/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0721/231300.002769:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::temp_directory_path: N'est pas un dossier: "/tmp/user/1000"`
